version: "3"

services:
  cr-golang-api:
    container_name: cr-golang-api
    image: cr-golang-api
    build:
      context: .
      dockerfile: api/.docker/golang/Dockerfile.dev
    env_file:
      - api/.docker/golang/.env
    volumes:
      - .:/go/src/github.com/Sharykhin/it-customer-review
    ports:
      - 8080:8080

  cr-golang-grpc-server:
    container_name: cr-golang-grpc-server
    image: cr-golang-grpc-server
    build:
      context: .
      dockerfile: grpc-server/.docker/golang/Dockerfile.dev
    env_file:
      - grpc-server/.docker/golang/.env
    volumes:
      - .:/go/src/github.com/Sharykhin/it-customer-review
    links:
      - cr-mysql-grpc-server-api
    depends_on:
      - cr-mysql-grpc-server-api
    ports:
      - 50051:50051

  cr-mysql-grpc-server-api:
    container_name: cr-mysql-grpc-server-api
    image: cr-mysql-grpc-server-api
    build:
      context: .
      dockerfile: grpc-server/.docker/mysql/Dockerfile
    env_file:
      - grpc-server/.docker/mysql/.env

  cr-golang-tone-analyzer:
    container_name: cr-golang-tone-analyzer
    image: cr-golang-tone-analyzer
    volumes:
      - .:/go/src/github.com/Sharykhin/it-customer-review
    build:
      context: .
      dockerfile: tone-analyzer/.docker/golang/Dockerfile.dev
    env_file:
      - tone-analyzer/.docker/golang/.env
    links:
      - cr-rabbitmq-tone-analyzer
    depends_on:
      - cr-rabbitmq-tone-analyzer

  cr-rabbitmq-tone-analyzer:
    container_name: cr-rabbitmq-tone-analyzer
    image: cr-rabbitmq-tone-analyzer
    build:
      context: .
      dockerfile: tone-analyzer/.docker/rabbitmq/Dockerfile.dev
    ports:
      - 5672:5672
      - 15672:15672
    env_file:
      - tone-analyzer/.docker/rabbitmq/.env
