kind: Service
apiVersion: v1
metadata:
  name: cr-grpc-service
  namespace: default
spec:
  ports:
  - port: 50051
    targetPort: 50051
  selector:
    name: grpc-server
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: grpc-server
  namespace: default
  labels:
    app: grpc-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: grpc-server
  template:
    metadata:
      labels:
        name: grpc-server
    spec:
      containers:
      - name: grpc-server-golang
        image: gcr.io/kubernetes-example-199908/grpc-server-golang:${VERSION}
        env:
        - name: GRPC_ADDRESS
          value: ":50051"
        - name: APP_ENV
          value: "dev"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: DB_HOST
          value: localhost
        - name: DB_NAME
          value: test
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=kubernetes-example-199908:us-central1:sql-example=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          secretName: cloudsql-instance-credentials