FROM golang:1.9

ENV APP_ENV dev

ADD . /go/src/github.com/Sharykhin/it-customer-review

WORKDIR /go/src/github.com/Sharykhin/it-customer-review

RUN go get . && \
    go get github.com/canthefason/go-watcher && \
    go get github.com/mattes/migrate && \
    go install github.com/canthefason/go-watcher/cmd/watcher && \
    go get -u gopkg.in/alecthomas/gometalinter.v2

EXPOSE 8080

ENTRYPOINT watcher