FROM golang:1.9

ENV APP_ENV prod

ADD . /go/src/github.com/Sharykhin/it-customer-review

WORKDIR /go/src/github.com/Sharykhin/it-customer-review/api

RUN curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

RUN dep ensure && \
    go build -o /go/bin/it-customer-review-api .

EXPOSE 8080

ENTRYPOINT /go/bin/it-customer-review-api
