FROM golang:1.9

ENV APP_ENV prod

ADD . /go/src/github.com/Sharykhin/it-customer-review

WORKDIR /go/src/github.com/Sharykhin/it-customer-review/api

RUN go get . && \
    go get github.com/gorilla/sessions && \
    go get github.com/stretchr/testify/mock && \
    go build -o /go/bin/it-customer-review-api .

EXPOSE 8080

ENTRYPOINT /go/bin/it-customer-review-api
