apiVersion: v1
kind: Service
metadata:
  name: web-ui-service
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: web-ui
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: web-ui
  namespace: default
  labels:
    app: web-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: web-ui
  template:
    metadata:
      labels:
        name: web-ui
    spec:
      containers:
      - name: web-ui
        image: gcr.io/kubernetes-example-199908/web-ui:${VERSION}
