FROM golang:1.9

ENV APP_ENV prod
ENV MYSQL_ADDRESS "test:test@tcp(localhost:3306)/test?parseTime=true"

ADD . /go/src/github.com/Sharykhin/it-customer-review

WORKDIR /go/src/github.com/Sharykhin/it-customer-review/grpc-server

RUN go get . && \
    go get github.com/go-sql-driver/mysql && \
    go build -o /go/bin/it-customer-review-grpc-server .

EXPOSE 50051

ENTRYPOINT /go/bin/it-customer-review-grpc-server
