FROM golang:1.9

ENV APP_ENV prod
ENV MYSQL_ADDRESS "test:test@tcp(localhost:3306)/test?parseTime=true"

ADD . /go/src/github.com/Sharykhin/it-customer-review-grpc-server

WORKDIR /go/src/github.com/Sharykhin/it-customer-review-grpc-server

RUN go get . && \
    go install github.com/Sharykhin/it-customer-review

EXPOSE 50051

ENTRYPOINT /go/bin/it-customer-review
