#!/bin/bash

if ([ $TRAVIS_BRANCH == "develop" ] && [ $TRAVIS_PULL_REQUEST == "false" ])
then
  VERSION=$(git rev-parse --short master)
  echo "Going to deploy staging on: ${VERSION}"
  echo "Application was deployed on ${VERSION}"
else
  echo "Build successful, but not publishing!"
fi
