// Code generated by protoc-gen-go. DO NOT EDIT.
// source: review.proto

/*
Package review is a generated protocol buffer package.

It is generated from these files:
	review.proto

It has these top-level messages:
	Empty
	Pong
	ReviewRequest
	ReviewResponse
*/
package review

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Pong struct {
	Response string `protobuf:"bytes,1,opt,name=response" json:"response,omitempty"`
}

func (m *Pong) Reset()                    { *m = Pong{} }
func (m *Pong) String() string            { return proto.CompactTextString(m) }
func (*Pong) ProtoMessage()               {}
func (*Pong) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Pong) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

// Request message for creating a new fail mail
type ReviewRequest struct {
	Name      string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=Email" json:"Email,omitempty"`
	Content   string `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
	Published bool   `protobuf:"varint,5,opt,name=Published" json:"Published,omitempty"`
	Score     int64  `protobuf:"varint,6,opt,name=Score" json:"Score,omitempty"`
	Category  string `protobuf:"bytes,7,opt,name=Category" json:"Category,omitempty"`
}

func (m *ReviewRequest) Reset()                    { *m = ReviewRequest{} }
func (m *ReviewRequest) String() string            { return proto.CompactTextString(m) }
func (*ReviewRequest) ProtoMessage()               {}
func (*ReviewRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ReviewRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReviewRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ReviewRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReviewRequest) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

func (m *ReviewRequest) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ReviewRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

// Response of fail mail
type ReviewResponse struct {
	ID        string `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Email     string `protobuf:"bytes,3,opt,name=Email" json:"Email,omitempty"`
	Content   string `protobuf:"bytes,4,opt,name=Content" json:"Content,omitempty"`
	Published bool   `protobuf:"varint,5,opt,name=Published" json:"Published,omitempty"`
	Score     int64  `protobuf:"varint,6,opt,name=Score" json:"Score,omitempty"`
	Category  string `protobuf:"bytes,7,opt,name=Category" json:"Category,omitempty"`
	CreatedAt string `protobuf:"bytes,8,opt,name=CreatedAt" json:"CreatedAt,omitempty"`
}

func (m *ReviewResponse) Reset()                    { *m = ReviewResponse{} }
func (m *ReviewResponse) String() string            { return proto.CompactTextString(m) }
func (*ReviewResponse) ProtoMessage()               {}
func (*ReviewResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReviewResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ReviewResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReviewResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ReviewResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *ReviewResponse) GetPublished() bool {
	if m != nil {
		return m.Published
	}
	return false
}

func (m *ReviewResponse) GetScore() int64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *ReviewResponse) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

func (m *ReviewResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "review.Empty")
	proto.RegisterType((*Pong)(nil), "review.Pong")
	proto.RegisterType((*ReviewRequest)(nil), "review.ReviewRequest")
	proto.RegisterType((*ReviewResponse)(nil), "review.ReviewResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Review service

type ReviewClient interface {
	Create(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error)
	Update(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error)
}

type reviewClient struct {
	cc *grpc.ClientConn
}

func NewReviewClient(cc *grpc.ClientConn) ReviewClient {
	return &reviewClient{cc}
}

func (c *reviewClient) Create(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error) {
	out := new(ReviewResponse)
	err := grpc.Invoke(ctx, "/review.Review/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) Update(ctx context.Context, in *ReviewRequest, opts ...grpc.CallOption) (*ReviewResponse, error) {
	out := new(ReviewResponse)
	err := grpc.Invoke(ctx, "/review.Review/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reviewClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Pong, error) {
	out := new(Pong)
	err := grpc.Invoke(ctx, "/review.Review/Ping", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Review service

type ReviewServer interface {
	Create(context.Context, *ReviewRequest) (*ReviewResponse, error)
	Update(context.Context, *ReviewRequest) (*ReviewResponse, error)
	Ping(context.Context, *Empty) (*Pong, error)
}

func RegisterReviewServer(s *grpc.Server, srv ReviewServer) {
	s.RegisterService(&_Review_serviceDesc, srv)
}

func _Review_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.Review/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).Create(ctx, req.(*ReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.Review/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).Update(ctx, req.(*ReviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Review_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReviewServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/review.Review/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReviewServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Review_serviceDesc = grpc.ServiceDesc{
	ServiceName: "review.Review",
	HandlerType: (*ReviewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Review_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Review_Update_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _Review_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "review.proto",
}

func init() { proto.RegisterFile("review.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 291 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x92, 0xc1, 0x4a, 0xfb, 0x40,
	0x10, 0xc6, 0xbb, 0x6d, 0x9a, 0xa4, 0x43, 0xdb, 0xc3, 0xf0, 0xff, 0xcb, 0x12, 0x3c, 0x84, 0x05,
	0x21, 0xa7, 0x1e, 0xf4, 0xe4, 0x51, 0x52, 0x0f, 0xbd, 0x48, 0x88, 0xf8, 0x00, 0xa9, 0x19, 0x62,
	0xa0, 0xcd, 0xc6, 0xcd, 0x56, 0xe9, 0xf3, 0x88, 0x2f, 0xe4, 0x13, 0xc9, 0xee, 0x26, 0x16, 0x3d,
	0x7a, 0xf2, 0xb6, 0xbf, 0x6f, 0x67, 0x86, 0x6f, 0x98, 0x0f, 0xe6, 0x8a, 0x5e, 0x6a, 0x7a, 0x5d,
	0xb5, 0x4a, 0x6a, 0x89, 0xbe, 0x23, 0x11, 0xc0, 0xf4, 0x76, 0xdf, 0xea, 0xa3, 0x10, 0xe0, 0x65,
	0xb2, 0xa9, 0x30, 0x82, 0x50, 0x51, 0xd7, 0xca, 0xa6, 0x23, 0xce, 0x62, 0x96, 0xcc, 0xf2, 0x2f,
	0x16, 0x6f, 0x0c, 0x16, 0xb9, 0xed, 0xcb, 0xe9, 0xf9, 0x40, 0x9d, 0x46, 0x04, 0xef, 0xae, 0xd8,
	0x13, 0x1f, 0xdb, 0x4a, 0xfb, 0xc6, 0x7f, 0x66, 0x64, 0x51, 0xef, 0xf8, 0xc4, 0x8a, 0x0e, 0x90,
	0x43, 0x90, 0xca, 0x46, 0x53, 0xa3, 0xb9, 0x67, 0xf5, 0x01, 0xf1, 0x1c, 0x66, 0xd9, 0x61, 0xbb,
	0xab, 0xbb, 0x27, 0x2a, 0xf9, 0x34, 0x66, 0x49, 0x98, 0x9f, 0x04, 0x33, 0xed, 0xfe, 0x51, 0x2a,
	0xe2, 0x7e, 0xcc, 0x92, 0x49, 0xee, 0xc0, 0xb8, 0x4c, 0x0b, 0x4d, 0x95, 0x54, 0x47, 0x1e, 0x38,
	0x97, 0x03, 0x8b, 0x0f, 0x06, 0xcb, 0xc1, 0xa5, 0x33, 0x8e, 0x4b, 0x18, 0x6f, 0xd6, 0xfd, 0x3a,
	0xe3, 0xcd, 0xfa, 0x2f, 0xda, 0x36, 0xf3, 0x52, 0x45, 0x85, 0xa6, 0xf2, 0x46, 0xf3, 0xd0, 0x7e,
	0x9e, 0x84, 0xcb, 0x77, 0x06, 0xbe, 0x5b, 0x0a, 0xaf, 0xc1, 0x77, 0x3a, 0xfe, 0x5f, 0xf5, 0x37,
	0xfd, 0x76, 0x94, 0xe8, 0xec, 0xa7, 0xdc, 0x9f, 0x6f, 0x64, 0x5a, 0x1f, 0xda, 0xf2, 0x57, 0xad,
	0x17, 0xe0, 0x65, 0x75, 0x53, 0xe1, 0x62, 0xa8, 0xb0, 0xb1, 0x89, 0xe6, 0x03, 0x9a, 0xf0, 0x88,
	0xd1, 0xd6, 0xb7, 0xf1, 0xba, 0xfa, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xd3, 0xcd, 0x47, 0x62, 0x6e,
	0x02, 0x00, 0x00,
}
