apiVersion: v1
kind: Service
metadata:
  name: api-server-service
  namespace: default
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    name: api-server
  type: LoadBalancer
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: api-server
  namespace: default
  labels:
    app: api-server
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      name: api-server
  template:
    metadata:
      labels:
        name: api-server
    spec:
      containers:
      - name: api-server-golang
        image: gcr.io/kubernetes-example-199908/api-server-golang:${VERSION}
        env:
        - name: HTTP_ADDRESS
          value: ":8080"
        - name: APP_ENV
          value: "dev"
        - name: CORS_ORIGIN
          value: "http://35.192.27.127"
        - name: AMPQ_ADDRESS
          value: "amqp://cr-rabbitmq-service:5672"
        - name: SESSION_KEY
          value: "B4B2F7F0D2A48D2AD4CCF65CC5DC360A37B8A6FB171627259531"
        - name: GRPC_ADDRESS
          value: "cr-grpc-service:50051"
        livenessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ping
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 10
