language: go
os: linux
go:
  - 1.9.x
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=client-secret.json
    - PROJECT_NAME=kubernetes-example-199908
    - CLUSTER_NAME=cluster-1
    - CLOUDSDK_COMPUTE_ZONE=us-central1-a
    - DOCKER_IMAGE_NAME=tone-analyzer-golang
    - KUBE_DEPLOYMENT_NAME=tone-analyzer
    - KUBE_DEPLOYMENT_CONTAINER_NAME=tone-analyzer-golang
services:
- docker
cache:
 directories:
  - "$HOME/google-cloud-sdk/"
install:
- go get -u gopkg.in/alecthomas/gometalinter.v2
- gometalinter.v2 --install
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./.deployment/travis/script-test; fi
before_deploy:
- openssl aes-256-cbc -K $encrypted_bd75f0e62987_key -iv $encrypted_bd75f0e62987_iv
  -in client-secret.json.enc -out ${GOOGLE_APPLICATION_CREDENTIALS} -d
- gcloud auth activate-service-account --key-file ${GOOGLE_APPLICATION_CREDENTIALS}
- gcloud container clusters get-credentials cluster-1 --zone us-central1-a --project kubernetes-example-199908
- if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
- source /home/travis/google-cloud-sdk/path.bash.inc
- bash ./.deployment/travis/remove-old-images
deploy:
  provider: script
  script: bash ./.deployment/travis/deploy-dev
  on:
    branch: develop

  provider: script
  script: bash ./.deployment/travis/deploy-prod
  on:
    branch: master
