FROM golang:1.9

ADD . /go/src/github.com/Sharykhin/it-customer-review

WORKDIR /go/src/github.com/Sharykhin/it-customer-review/queue-manager

RUN go get . && \
    go build -o /go/bin/it-customer-review-queue-manager .

EXPOSE 5672
EXPOSE 15672

ENTRYPOINT /go/bin/it-customer-review-queue-manager
